### ISSUE TITLE
Research testing framework

### ISSUE THREAD

**Issue by mirdaki** [ufosc/club-admin-portal#12]
We will need to write unit test to make sure the website is working and help prevent regressions. They will need to support mocking REST calls (so we can test without a database). Feel free to do some research.

Could we get a discussion going about preferences, what works best with Vue, etc?

**Comment by dylanalvarez1** [comment]
@mirdaki What do you think about using MochaJS and ChaiJS with Node for testing? I found a lot of scotch.io tutorials on using them to test RESTful APIs

**Comment by mirdaki** [comment]
Here is a (very opinionated) [article](https://andrew.codes/jest-vs-mocha-why-jest-wins/) about Jest. It seems to have a lot of nice default things (like automatic mocking). @dylanalvarez1 and @ankitprahladsoni thoughts?

**Comment by ankitprahladsoni** [comment]
Although Mocha + Chai is more mature, Jest is easier to learn and have clear syntax and community is driving towards it.
That's all I can say from my 2-week work with Jest and Mocha + Chai.

**Comment by mirdaki** [comment]
Hahaha, I think we will use Jest then. The repo should already have some basic Jest stuff setup, so we should be good to go!
